export const FETCH_SEARCHED_FILMS = "FETCH_SEARCHED_FILMS";
export const ADD_SEARCHED_FILMS = "ADD_SEARCHED_FILMS";
export const FETCH_FILM_DATA = "FETCH_FILM_DATA";
export const ADD_FILM_DATA = "ADD_FILM_DATA";

export const TOGGLE_FILM_TO_FAVORITE = "ADD_FILM_TO_FAVORITE";
