enum actions {
  FETCH_SEARCHED_FILMS = "FETCH_SEARCHED_FILMS",
  ADD_SEARCHED_FILMS = "ADD_SEARCHED_FILMS",
  FETCH_FILM_DATA = "FETCH_FILM_DATA",
  ADD_FILM_DATA = "ADD_FILM_DATA",
}

export default actions;
